### ISSUE TITLE
hyperdb deprecated? Move to hypertrie?

### ISSUE THREAD

**Issue by eklem** [geut/dat-workshop#23]
Hi, heard that the Dat project is moving from hyperdb to hypertrie. Will the workshop include this update when it's ready?

**Comment by dpaez** [comment]
Hi @eklem 👋,
Yeah, the idea is to keep the workshop up to date. We should start working on it pretty soon, also there is hyperdrive v10, dat-sdk and hyperswarm to mention. (Basically we should be using Dat 2.0 I guess). 
I can't give a you an ETA yet,  but as I said, we should be starting soon. 

We will be blogging about it on [our blog](https://geutstudio.com/blog/).

If you have any other questions or ideas to share, please go ahead.

**Comment by eklem** [comment]
Thanks, I'll test out the workshop anyway I think, just to get into stuff.

**Comment by tinchoz49** [comment]
Hi @eklem, how are you?

Yes we've plans for update the workshop.

About hyperdb to hypertrie:

We use hyperdb as a solution to build a multi-writer app in Dat. Hypertrie solves a different problem and it's single-writer.

Probably we should think about updating the workshop to use kappa-db + multifeed (what cabal is using)

> Thanks, I'll test out the workshop anyway I think, just to get into stuff.

Yeah! give a try, the most important objective in this workshop is to learn the basic concepts that you need to know to build your p2p ideas on top. Hyperdb is just a tool in that process.

**Comment by dpaez** [comment]
Cool! Go ahead, it is still a valid workshop and can give you a good idea of how to build a decentralized app. PRs/feedback is always welcome! 😄

**Comment by eklem** [comment]
Thanks :-)
